# Generated by Django 3.0.5 on 2020-05-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='lati',
            field=models.IntegerField(default=1, verbose_name='lati'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura',
            name='longi',
            field=models.IntegerField(default=1, verbose_name='longi'),
            preserve_default=False,
        ),
    ]
