# Generated by Django 3.0.5 on 2020-05-13 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Temperatura', '0002_auto_20200513_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='tipTerr',
            field=models.TextField(default=django.utils.timezone.now, max_length=140, verbose_name='tipTerr'),
            preserve_default=False,
        ),
    ]
